<a href="https://colab.research.google.com/github/ManisMalakar/Convolutional-Neural-Network-/blob/main/Object_Recognition_in_Images_with_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [71]:
import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt

In [72]:
#Data PreProcessing

#Importing the dataset
from tensorflow.keras.datasets import cifar10

In [73]:
#Loading the dataset
(x_train, y_train),(x_test,y_test)=cifar10.load_data()

In [74]:
class_names = ['0: airplane', '1: automobile', '2: bird', '3: cat', '4: deer', '5: dog', '6: frog', '7: horse', '8: ship', '9: truck']

In [75]:
#Normalizing the images
x_train=x_train/255.0
x_test=x_test/255.0

In [76]:
y_train.max(),y_train.min(),y_train.mean()

(9, 0, 4.5)

In [77]:
x_train.max(),x_train.min(),x_train.mean()

(1.0, 0.0, 0.4733630004850874)

In [78]:
#Building the CNN
model=tf.keras.models.Sequential()

In [79]:
#Adding the first CNN layer
#1. Number of filters or kernels=32
#2. Kernel Size=3
#3. Padding=Same
#4. Activation Function=ReLu
#5. Input Shape=(32,32,3)

model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding='same',activation='relu',input_shape=[32,32,3]))

In [80]:
#Adding the second CNN layer
#1. Number of filters or kernels=32
#2. Kernel Size=3
#3. Padding=Same
#4. Activation Function=ReLu

model.add(tf.keras.layers.Conv2D(filters=32,kernel_size=3,padding='same',activation='relu'))

In [81]:
#Maxpool Layer Parameters,
#1. Pool Size=2
#2. Strides=2
#3. Padding=Value

model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2,padding='valid'))

In [82]:
#Adding the third CNN layer
#1. Number of filters or kernels=64
#2. Kernel Size=3
#3. Padding=Same
#4. Activation Function=ReLu

model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))

In [83]:
#Adding the fourth CNN layer
#1. Number of filters or kernels=64
#2. Kernel Size=3
#3. Padding=Same
#4. Activation Function=ReLu

model.add(tf.keras.layers.Conv2D(filters=64,kernel_size=3,padding='same',activation='relu'))

In [84]:
# Adding second Maxpool Layer Parameters,
#1. Pool Size=2
#2. Strides=2
#3. Padding=Value

model.add(tf.keras.layers.MaxPool2D(pool_size=2,strides=2,padding='valid'))

In [85]:
# Adding the dropout layer
model.add(tf.keras.layers.Dropout(0.4))

#Adding the Flattening Technique
model.add(tf.keras.layers.Flatten())

#Adding the First Dense Layer
model.add(tf.keras.layers.Dense(units=128,activation='relu'))

In [86]:
#Adding the Second Dense Layer- Output Layer
model.add(tf.keras.layers.Dense(units=10,activation='softmax'))

In [87]:
#Training the Model
# Compiling the model
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['sparse_categorical_accuracy'])


In [88]:
model.fit(x_train, y_train, batch_size=10, epochs=10)

Epoch 1/10
5000/5000 [==============================] - 322s 64ms/step - loss: 1.6518 - sparse_categorical_accuracy: 0.3938
Epoch 2/10
5000/5000 [==============================] - 324s 65ms/step - loss: 1.0387 - sparse_categorical_accuracy: 0.6310
Epoch 3/10
5000/5000 [==============================] - 321s 64ms/step - loss: 0.8743 - sparse_categorical_accuracy: 0.6875
Epoch 4/10
5000/5000 [==============================] - 317s 63ms/step - loss: 0.7792 - sparse_categorical_accuracy: 0.7228
Epoch 5/10
5000/5000 [==============================] - 320s 64ms/step - loss: 0.7118 - sparse_categorical_accuracy: 0.7485
Epoch 6/10
5000/5000 [==============================] - 318s 64ms/step - loss: 0.6515 - sparse_categorical_accuracy: 0.7699
Epoch 7/10
5000/5000 [==============================] - 316s 63ms/step - loss: 0.6077 - sparse_categorical_accuracy: 0.7849
Epoch 8/10
5000/5000 [==============================] - 319s 64ms/step - loss: 0.5769 - sparse_categorical_accuracy: 0.7956
Epoch 9/

In [96]:
#Evaluate the model performance
test_loss,test_acc=model.evaluate(x_test,y_test)

313/313 [==============================] - 14s 43ms/step - loss: 0.7598 - sparse_categorical_accuracy: 0.7452


In [97]:
print('Test Accuracy = {}'.format(test_acc))

Test Accuracy = 0.745199978351593


In [98]:
#Predictions
y_pred=model.predict_classes(x_test)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/sequential.py:450: UserWarning: `model.predict_classes()` is deprecated and will be removed after 2021-01-01. Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
  warnings.warn('`model.predict_classes()` is deprecated and '


In [101]:
print(y_pred[120]), print(y_test[120])

8
[8]


(None, None)

In [104]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm=confusion_matrix(y_test,y_pred)
print(cm)

[[750  15  48  28  18   1   7  10  71  52]
 [  5 871   2   5   4   1   3   2  21  86]
 [ 76   4 605  72  78  50  38  46  18  13]
 [ 28   5  47 541  56 185  42  50  20  26]
 [ 23   3  62  60 677  46  33  76  13   7]
 [  9   2  38 147  32 653  20  82   8   9]
 [  9   3  44  63  40  34 775  10  10  12]
 [ 10   5  27  24  44  46   1 819   8  16]
 [ 37  25   4   7   3   9   4   6 882  23]
 [ 14  51   4  10   2   4   5   6  25 879]]


In [105]:
acc_cm=accuracy_score(y_test,y_pred)
print(acc_cm)

0.7452
